### ISSUE TITLE
AttachToContainer won't disconnect when container dies

### ISSUE THREAD

**Issue by amasad** [fsouza/go-dockerclient#209]
If the container dies unexpectedly `AttachToContainer` will continue to block. I'm listening on events and the container obviously died. The only time the call will cease to block is if we destroy the container. Coupled with #161 where we can't cancel the operation, this means we're leaking connections to the daemon which is how I found this bug,

**Comment by fsouza** [comment]
If you restart your container, after it dies, is your program still attached to the container?

**Comment by amasad** [comment]
Yes, however, I think it's somewhat a user error. I had a bug that didn't close the Stdin object on the attached container. Now that I'm returning EOF from the io.Reader passed to the AttachToContainer it's actually exiting.

**Comment by pwaller** [comment]
I'm having a problem that sounds exactly like this. I instrumented the writer like so: [Link to a more full description](https://gist.github.com/pwaller/b21e452e0d9ed38d8441).

Essentially, about one in four runs, the program hangs and `AttachToContainer` doesn't return. I'm just trying to grab the standard output. I'm writing a few megabytes of binary (a tar stream) to standard output. The same binary stream sometimes succeeds and sometimes fails.

I instrumented the writer, and I observe that on the successful runs, the Write() method is being called with a full buffer. On the unsuccessful runs, it's being called with random small-sized buffers, which seems like it might be a race condition.

I cannot reproduce this with plain old docker commands.

If I sent the process SIGQUIT, I get no output (GRR), so I can't obtain a stack trace for reasons I don't yet understand. Still working on it.

**Comment by pwaller** [comment]
Just to add, whenever the program does hangs, the size of the last write seems to be around 50 bytes, despite there being plenty of writes of other magnitudes.

**Comment by pwaller** [comment]
Unfortunately, I can only reproduce this on a cloud machine (docker 1.7.1), and not on my desktop (docker 1.8.3). I suppose it may either be a problem with the older docker machine, or relate to machine speed? I'll continue to investigate tonight.

I managed to coax the stack out. I think systemd or journalctl were swallowing it somehow?

* [Where we're stuck in the attach call](https://github.com/fsouza/go-dockerclient/blob/ef410296f87750305e1e1acf9ad2ba3833dcb004/client.go#L652)

* [Where we're stuck inside stdcopy](https://github.com/fsouza/go-dockerclient/blob/master/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go#L97)

```
SIGQUIT: quit
PC=0x45e859 m=0

goroutine 0 [idle]:
runtime.epollwait(0x7fff00000004, 0x7fff9a2511d0, 0xffffffff00000080, 0x0, 0xffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:420 +0x19
runtime.netpoll(0x9ae001, 0x0)
	/usr/local/go/src/runtime/netpoll_epoll.go:68 +0x94
runtime.findrunnable(0xc82001b500, 0x0)
	/usr/local/go/src/runtime/proc1.go:1512 +0x598
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc820001980)
	/usr/local/go/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7fff9a2518e0)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Syncsemacquire(0xc8200a4340)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8200a4330)
	/usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc8200a4300, 0xc8200f0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc8200263f0, 0xc8200f0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x50
go.(*struct { io.Reader; io.Closer }).Read(0xc82000be40, 0xc8200f0000, 0x8000, 0x8000, 0x1bf0, 0x0, 0x0)
	<autogenerated>:2 +0x82
io.copyBuffer(0x7f437b9101c0, 0xc820026010, 0x7f437b911bd0, 0xc82000be40, 0xc8200f0000, 0x8000, 0x8000, 0x4cb7df, 0x0, 0x0)
	/usr/local/go/src/io/io.go:381 +0x247
io.Copy(0x7f437b9101c0, 0xc820026010, 0x7f437b911bd0, 0xc82000be40, 0xc82000be40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x64
main.main()
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/cmd/t/t.go:36 +0x3e7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 8 [chan receive]:
github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient.(*Client).hijack(0xc82007b050, 0x7d53e0, 0x4, 0xc820076980, 0x75, 0x0, 0x0, 0x0, 0x0, 0x7f437b911c70, ...)
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient/client.go:652 +0x944
github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient.(*Client).AttachToContainer(0xc82007b050, 0xc8200c8140, 0x40, 0x0, 0x0, 0x7f437b911c70, 0xc8200adb70, 0x7f437b9101c0, 0xc820026018, 0x101000101, ...)
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient/container.go:1031 +0x2ba
main.DockerRun.func1(0xc82007b050, 0xc8200ce000, 0xc8200263f8)
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/cmd/t/t.go:70 +0x18d
created by main.DockerRun
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/cmd/t/t.go:82 +0x6c7

goroutine 6 [IO wait]:
net.runtime_pollWait(0x7f437b9117f0, 0x72, 0xc820010170)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200b03e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200b03e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200b0380, 0xc8200a3000, 0x1000, 0x1000, 0x0, 0x7f437b90c050, 0xc820010170)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200263e0, 0xc8200a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f437b9118b0, 0xc8200263e0, 0xc8200aa108, 0xc8200a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82000bce0, 0xc8200a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820018720)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820018720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200aa0b0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 7 [select]:
net/http.(*persistConn).writeLoop(0xc8200aa0b0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f437b911730, 0x72, 0xc820010170)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200b05a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200b05a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200b0540, 0xc8200fa000, 0x8009, 0x8009, 0x0, 0x7f437b90c050, 0xc820010170)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026400, 0xc8200fa000, 0x8009, 0x8009, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).Read(0xc820018900, 0xc8200fa000, 0x8009, 0x8009, 0x1bf0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:197 +0x126
github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy.StdCopy(0x7f437b911c70, 0xc8200adb70, 0x7f437b9101c0, 0xc820026018, 0x7f4379ad8000, 0xc820018900, 0x4cb7df, 0x0, 0x0)
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:97 +0x17a
github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient.(*Client).hijack.func1(0x0, 0x0, 0x0, 0x0, 0x7f437b911c70, 0xc8200adb70, 0x7f437b9101c0, 0xc820026018, 0x0, 0x0, ...)
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient/client.go:636 +0x1cf
created by github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient.(*Client).hijack
	/home/pwaller/.local/src/github.com/scraperwiki/hanoverd/vendor/github.com/fsouza/go-dockerclient/client.go:639 +0xa4f

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x45e859
rdx    0x80
rdi    0x4
rsi    0x7fff9a2511d0
rbp    0x9ae900
rsp    0x7fff9a251190
r8     0x9ae900
r9     0x0
r10    0xffffffff
r11    0x246
r12    0x0
r13    0x1bf0
r14    0x10
r15    0x8128e0
rip    0x45e859
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by pwaller** [comment]
Okay, I've reproduced this on docker 1.7.1 on the non-cloud machine. I've also seen a load of other weird behaviour. For instance, io.Copy returning no bytes. Or all of the writes being 65 bytes large followed by giving EOF after only 10kiB of the 5MiB stream.

**Comment by pwaller** [comment]
It's still quite hard to reproduce. It seems to only happen one in tens of times locally. (One in a few on the AWS instance)

**Comment by pwaller** [comment]
Okay, I just managed to reproduce the problem on docker 1.8.3 as well. It seems actually quite difficult to reproduce locally, requiring very many runs.
