### ISSUE TITLE
Can't build image using Dockerfile

### ISSUE THREAD

**Issue by nlamirault** [fsouza/go-dockerclient#251]
hi
hi try to build an image from a Dockerfile : 

```go
var buf bytes.Buffer
opts := docker.BuildImageOptions{
	Name:           "clyde/" + name,
	Dockerfile:     "/tmp/foo/Dockerfile",
	SuppressOutput: true,
	OutputStream:   &buf,
}
err := client.BuildImage(opts)
if err != nil {
	return err
}
log.Debugf("Docker image: %s", buf.String())
```

I've got an error : 

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5cd022]

goroutine 32 [running]:
runtime.panic(0x7fc800, 0xab3413)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/fsouza/go-dockerclient.(*Client).stream(0xc2080ee100, 0x854790, 0x4, 0xc2080d8cb0, 0x6f, 0xc2080d0001, 0xc2080d71a0, 0x7f82e61c34b0, 0xc2080d74a0, 0x7f82e61c1aa8, ...)
        /home/vagrant/Apps/clyde/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:389 +0x10c2
github.com/fsouza/go-dockerclient.(*Client).BuildImage(0xc2080ee100, 0xc2080e2800, 0x9, 0x896ad0, 0x13, 0x100, 0x0, 0x0, 0x7f82e61c1aa8, 0xc2080d8930, ...)
        /home/vagrant/Apps/clyde/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/image.go:386 +0x47f
```

Any idea ?
Thanks.

**Comment by fsouza** [comment]
Hmm, that's interesting. This should not be happening, do you get any error or just the panic? I will try to run your sample locally.

Thanks for reporting!

**Comment by fsouza** [comment]
@nlamirault is your Docker server bound to a TCP port or Unix socket?

Thanks!

**Comment by nlamirault** [comment]
I've got only this : 

```bash
ls /etc/docker/
certs.d
```

```bash

$ cat /usr/lib/systemd/system/docker.socket
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target


$ cat /etc/systemd/system/multi-user.target.wants/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
ExecStart=/usr/bin/docker -d -H fd://
LimitNOFILE=1048576
LimitNPROC=1048576

[Install]
WantedBy=multi-user.target
```

**Comment by james-nesbitt** [comment]
can you include the line where you create the client please.  I had the same issue when I was using an invalid factory call.

**Comment by nlamirault** [comment]
I make a new test it works. Sorry for noise
