### ISSUE TITLE
Dead lock in docker events not resolved in latest version

### ISSUE THREAD

**Issue by slene** [fsouza/go-dockerclient#311]
@fsouza https://github.com/fsouza/go-dockerclient/issues/203 not fix this bug

```
goroutine 7 [semacquire, 1 minutes]:
sync.(*RWMutex).Lock(0xc2080119d0)
	/usr/local/go/src/sync/rwmutex.go:87 +0xa4
github.com/fsouza/go-dockerclient.(*eventMonitoringState).updateLastSeen(0xc2080119d0, 0xc20809ed00)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:242 +0x33
github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xc2080119d0, 0xc20806a280)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:185 +0x245
created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:148 +0x16f

goroutine 95 [semacquire, 1 minutes]:
sync.(*RWMutex).RLock(0xc2080119d0)
	/usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/fsouza/go-dockerclient.(*eventMonitoringState).isEnabled(0xc2080119d0, 0x0)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:219 +0x34
github.com/fsouza/go-dockerclient.func·006(0xc2080642d0, 0xc2080c4000)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:302 +0x353
created by github.com/fsouza/go-dockerclient.(*Client).eventHijack
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:307 +0x625

goroutine 58206 [semacquire, 1 minutes]:
sync.(*RWMutex).RLock(0xc2080119d0)
	/usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/fsouza/go-dockerclient.(*eventMonitoringState).isEnabled(0xc2080119d0, 0x0)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:219 +0x34
github.com/fsouza/go-dockerclient.(*eventMonitoringState).sendEvent(0xc2080119d0, 0xc20809eb80)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:229 +0xc9
created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:186 +0x26a

goroutine 58207 [semacquire, 1 minutes]:
sync.(*RWMutex).RLock(0xc2080119d0)
	/usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/fsouza/go-dockerclient.(*eventMonitoringState).sendEvent(0xc2080119d0, 0xc20809ec80)
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:225 +0x33
created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents
	/Users/slene/src/github.com/fsouza/go-dockerclient/event.go:186 +0x26a
```

**Comment by slene** [comment]
closed this, discuss in pr https://github.com/fsouza/go-dockerclient/pull/312
