### ISSUE TITLE
Having trouble with Docker-Machine (VirtualBox on a Mac)

### ISSUE THREAD

**Issue by gzoller** [fsouza/go-dockerclient#395]
Hello,

My Mac's Docker daemon is started like this:

<img width="804" alt="screen shot 2015-10-10 at 11 28 24 pm" src="https://cloud.githubusercontent.com/assets/772873/10414683/c717d33c-6fa6-11e5-8b15-4eea521b1516.png">

So based on that I hard-coded some values like so:

```package main

import (
    "fmt"
    "github.com/fsouza/go-dockerclient"
)

func main() {
    endpoint := "tcp://0.0.0.0:2376"
    path := "/var/lib/boot2docker"
    ca := fmt.Sprintf("%s/ca.pem", path)
    cert := fmt.Sprintf("%s/server.pem", path)
    key := fmt.Sprintf("%s/server-key.pem", path)
    client, _ := docker.NewTLSClient(endpoint, cert, key, ca)

    imgs, _ := client.ListImages(docker.ListImagesOptions{All: false})
    for _, img := range imgs {
        fmt.Println("ID: ", img.ID)
        fmt.Println("RepoTags: ", img.RepoTags)
        fmt.Println("Created: ", img.Created)
        fmt.Println("Size: ", img.Size)
        fmt.Println("VirtualSize: ", img.VirtualSize)
        fmt.Println("ParentId: ", img.ParentID)
    }
}```

When I ran this program I got the error shown below.  Am I doing something wrong?  Thanks!

```panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4763ca]

goroutine 1 [running]:
github.com/fsouza/go-dockerclient.(*Client).do(0x0, 0x7cfea8, 0x3, 0x7d5f50, 0xd, 0x0, 0x0, 0x9a2700, 0x0, 0x0, ...)
	/go/src/github.com/fsouza/go-dockerclient/client.go:390 +0x63a
github.com/fsouza/go-dockerclient.(*Client).ListImages(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/fsouza/go-dockerclient/image.go:99 +0x182
main.main()
	/work/src/greg/greg2.go:20 +0x427

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2```

**Comment by gzoller** [comment]
It was a key problem.  I wish VirtualBox/Docker shipped w/o TLS enabled by default!
