### ISSUE TITLE
Question: Panic error with basic example

### ISSUE THREAD

**Issue by gianarb** [fsouza/go-dockerclient#430]
Hello,
Thanks for your work, I don't know if it is a problem of my script or not but I am trying to work with
docker tools on my mac installed by docker toolbox.

I wrote this little script
```go
package main

import (
	"fmt"
	"github.com/fsouza/go-dockerclient"
)

func main() {
	client, _ := docker.NewTLSClient(
		"http://192.168.99.100:2376",
		"/Users/garbezzano/.docker/machine/machines/default/cert.pem",
		"/Users/garbezzano/.docker/machine/machines/default/key.pem",
		"/Users/garbezzano/.docker/machine/machines/default/ca.pem")

	imgs, err := client.ListImages(docker.ListImagesOptions{All: false})
	if err != nil {
		fmt.Printf("%s\n", err)
	}
        for _, img := range imgs {
             fmt.Println("ID: ", img.ID)
        }
}
```
When I run it I receive this error
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4760fa]

goroutine 1 [running]:
github.com/fsouza/go-dockerclient.(*Client).do(0x0, 0x7d44c0, 0x3, 0x7da570, 0xd, 0x0, 0x0, 0x0, 0x0, 0x40fa69, ...)
        /work/src/github.com/fsouza/go-dockerclient/client.go:388 +0x63a
github.com/fsouza/go-dockerclient.(*Client).ListImages(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /work/src/github.com/fsouza/go-dockerclient/image.go:100 +0x1a2
main.main()
        /work/main.go:15 +0xdd

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
exit status 2
```

I tried with a wget and my API works
```
wget --no-check-certificate --certificate=$DOCKER_CERT_PATH/cert.pem --private-key=$DOCKER_CERT_PATH/key.pem https://192.168.99.100:2376/images/json -O - -q
```

I am working with golang 1.5.2
Thanks!

**Comment by fsouza** [comment]
@gianarb please check the error in the NewTLSClient call, seems like it's returning a nil client and an error.

**Comment by gianarb** [comment]
oh I am very crazy.. Sorry, yes

```
open /Users/garbezzano/.docker/machine/machines/default/cert.pem: no such file or directory
```
but this file exists..

**Comment by fsouza** [comment]
What's the output of the command below?

```
% file /Users/garbezzano/.docker/machine/machines/default/cert.pem
```

**Comment by gianarb** [comment]
```
-bash: fg: %: no such job
```

**Comment by gianarb** [comment]
Resolved!! Sorry for to grab your time!
Thanks for your work!

**Comment by fsouza** [comment]
@gianarb I'm glad you figured it out. Feel free to open new issues in the future!
