### ISSUE TITLE
TestSwarmJoinWithService fails due to segfault

### ISSUE THREAD

**Issue by raboof** [fsouza/go-dockerclient#616]
On a fresh checkout, 'make test' appears to fail due to a TLS handshake error for me.

```
go test  ./...
ok  	github.com/fsouza/go-dockerclient	5.001s
2017/01/23 17:03:49 http: TLS handshake error from 127.0.0.1:35258: EOF
--- FAIL: TestSwarmJoinWithService (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x56061c9b365a]

goroutine 291 [running]:
panic(0x56061cc14ee0, 0xc42000c140)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420706d80)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x56061cc14ee0, 0xc42000c140)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/fsouza/go-dockerclient/testing.compareServices(0xc42038ef00, 0xc42038f900, 0xc42011fc00)
	/home/aengelen/dev/go/src/github.com/fsouza/go-dockerclient/testing/swarm_test.go:514 +0x7a
github.com/fsouza/go-dockerclient/testing.TestSwarmJoinWithService(0xc420706d80)
	/home/aengelen/dev/go/src/github.com/fsouza/go-dockerclient/testing/swarm_test.go:224 +0x96d
testing.tRunner(0xc420706d80, 0x56061ccacba0)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2ec
FAIL	github.com/fsouza/go-dockerclient/testing	1.412s
Makefile:33: recipe for target 'gotest' failed
make: *** [gotest] Error 1
```

**Comment by raboof** [comment]
Ah actually it doesn't appear to have anything to do with TLS, with `go test ./... -run TestSwarmJoinWithService` I get only:
```
ok  	github.com/fsouza/go-dockerclient	0.004s
--- FAIL: TestSwarmJoinWithService (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5578affa565a]

goroutine 6 [running]:
panic(0x5578b0206ee0, 0xc420012100)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420092480)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x5578b0206ee0, 0xc420012100)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/fsouza/go-dockerclient/testing.compareServices(0xc4203dc280, 0xc4201da280, 0xc4203a2240)
	/home/aengelen/dev/go/src/github.com/fsouza/go-dockerclient/testing/swarm_test.go:514 +0x7a
github.com/fsouza/go-dockerclient/testing.TestSwarmJoinWithService(0xc420092480)
	/home/aengelen/dev/go/src/github.com/fsouza/go-dockerclient/testing/swarm_test.go:224 +0x96d
testing.tRunner(0xc420092480, 0x5578b029eba0)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2ec
FAIL	github.com/fsouza/go-dockerclient/testing	0.012s
```

**Comment by raboof** [comment]
Hum, seems I was on an outdated version after all, sorry :(
